language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-nikita' ]; then cd .. && eval "mv $currentfolder generator-nikita" && cd generator-nikita; fi

